// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Client = require("@prisma/client");

var prisma = new Client.PrismaClient();

var prismaContext = {
  prisma: prisma
};

exports.prisma = prisma;
exports.prismaContext = prismaContext;
/* prisma Not a pure module */
