// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var GraphqlYoga = require("graphql-yoga");
var Query$GraphqlYogaRescript = require("./resolvers/Query.bs.js");
var Context$GraphqlYogaRescript = require("./context.bs.js");

var graphQLConfig_typeDefs = Fs.readFileSync("/Users/tlonist/Documents/company/greenlabs/graphql-yoga-rescript/src/schema.graphql", "utf8");

var graphQLConfig = {
  typeDefs: graphQLConfig_typeDefs,
  resolvers: Query$GraphqlYogaRescript.categories,
  context: Context$GraphqlYogaRescript.prismaContext
};

var server = new GraphqlYoga.GraphQLServer(graphQLConfig);

server.start(function (param) {
      console.log("Running at 4000!");
      
    });

var resolvers = Query$GraphqlYogaRescript.categories;

exports.resolvers = resolvers;
exports.graphQLConfig = graphQLConfig;
exports.server = server;
/* graphQLConfig Not a pure module */
